#!/usr/bin/env python3
"""
DevLog Sync Script

Features:
1. Read config from ~/.devlog/config.md (or DEVLOG_ROOT env var)
2. Scan daily/ logs, extract @ProjectName tags, generate projects/
3. Archive inbox.md to daily/ (auto-distribute by timestamp)
4. Generate daily statistics table
5. Generate weekly report

Usage:
    python -m devlog.sync                    # Default: sync today + generate stats
    python -m devlog.sync --sync             # Sync daily to projects
    python -m devlog.sync --archive-inbox    # Archive inbox.md
    python -m devlog.sync --daily-stats      # Generate statistics
    python -m devlog.sync --weekly           # Generate weekly report
"""

import argparse
import logging
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
)

from .config import DevLogConfig


class DevLogSync:
    def __init__(self, root_dir=None):
        self.config = DevLogConfig(root_dir)
        self.root = self.config.root_dir
        self.symbols = self.config.get_symbols()

    def _daily_path(self, date_str):
        return self.root / "daily" / f"{date_str}.md"

    def _ensure_daily(self, date_str):
        """Ensure daily file exists, create from template if missing."""
        path = self._daily_path(date_str)
        if path.exists():
            return path

        lang = self.config.language
        if lang == "auto":
            lang = self.config._detect_language()

        template_name = "daily.md" if lang == "zh" else "daily.en.md"
        template = self.root / ".devlog" / "templates" / template_name

        weekday_map = {
            "Mon": "周一", "Tue": "周二", "Wed": "周三",
            "Thu": "周四", "Fri": "周五", "Sat": "周六", "Sun": "周日"
        }
        weekday_en = datetime.strptime(date_str, "%Y-%m-%d").strftime("%a")
        weekday_label = weekday_map.get(weekday_en, weekday_en) if lang == "zh" else weekday_en

        if template.exists():
            content = template.read_text(encoding="utf-8")
        else:
            content = self._default_daily_template(lang=lang)

        content = content.replace("{{DATE}}", date_str).replace("{{WEEKDAY}}", weekday_label)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def _default_daily_template(self, lang="zh"):
        s = self.symbols
        if lang == "zh":
            return (
                "# {{DATE}} {{WEEKDAY}}\n\n"
                f"> 关键词：\n\n"
                f"## 🕐 Interstitial Log\n\n"
                f"<!-- AI appends records here -->\n\n"
                f"## 🧠 Reflections\n\n"
                f"<!-- Optional: fill during review -->\n\n"
                f"## 📊 Daily Stats\n\n"
                f"> Auto-generated by `sync.py --daily-stats`\n\n"
                f"<!-- STATS_TABLE_START -->\n"
                f"| Type | Count | Percentage |\n"
                f"|------|-------|------------|\n"
                f"| Note {s['note']} | 0 | 0% |\n"
                f"| Problem {s['problem']} | 0 | 0% |\n"
                f"| Learning {s['learning']} | 0 | 0% |\n"
                f"| Idea {s['idea']} | 0 | 0% |\n"
                f"| Todo {s['todo']}→{s['done']} | 0→0 | 0% |\n"
                f"<!-- STATS_TABLE_END -->\n\n"
                f"## 😊 情绪追踪\n\n"
                f"<!-- 在一天结束时添加情绪评分，例如：(mood: 4/5) -->\n\n"
                f"## 🔗 Related Projects\n\n"
                f"<!-- Auto-generated by sync.py -->\n"
            )
        return (
            "# {{DATE}} {{WEEKDAY}}\n\n"
            f"> Keywords:\n\n"
            f"## 🕐 Interstitial Log\n\n"
            f"<!-- AI appends records here -->\n\n"
            f"## 🧠 Reflections\n\n"
            f"<!-- Optional: filled during daily review -->\n\n"
            f"## 📊 Daily Stats\n\n"
            f"> Auto-generated by `sync.py --daily-stats`\n\n"
            f"<!-- STATS_TABLE_START -->\n"
            f"| Type | Count | Percentage |\n"
            f"|------|-------|------------|\n"
            f"| Note {s['note']} | 0 | 0% |\n"
            f"| Problem {s['problem']} | 0 | 0% |\n"
            f"| Learning {s['learning']} | 0 | 0% |\n"
            f"| Idea {s['idea']} | 0 | 0% |\n"
            f"| Todo {s['todo']}→{s['done']} | 0→0 | 0% |\n"
            f"<!-- STATS_TABLE_END -->\n\n"
            f"## 😊 Mood Tracker\n\n"
            f"<!-- Add mood at end of day: (mood: 4/5) -->\n\n"
            f"## 🔗 Related Projects\n\n"
            f"<!-- Auto-generated by sync.py -->\n"
        )

    def _parse_log_line(self, line):
        """Parse a log line, return structured data or None.

        Supports optional time range: [09:00-10:30]
        """
        SINGLE = r'[·×○✓→*x!\-]'
        PAIR = r'\[ \]|\[v\]|>>'
        pattern = rf'^\[(\d{{2}}:\d{{2}})(?:-(\d{{2}}:\d{{2}}))?\]\s+({SINGLE}|{PAIR})\s+(.+)$'
        m = re.match(pattern, line.strip())
        if not m:
            return None
        start_time, end_time, symbol, content = m.groups()
        tags = re.findall(r'@(\S+)', content)
        hashtags = re.findall(r'#(\S+)', content)

        result = {
            "time": start_time,
            "symbol": symbol,
            "content": content,
            "tags": tags,
            "hashtags": hashtags,
        }

        if end_time:
            try:
                fmt = "%H:%M"
                start_dt = datetime.strptime(start_time, fmt)
                end_dt = datetime.strptime(end_time, fmt)
                duration = int((end_dt - start_dt).total_seconds() / 60)
                if duration < 0:
                    duration += 24 * 60  # cross midnight
                result["duration"] = duration
                result["end_time"] = end_time
            except ValueError:
                pass

        return result

    def _classify_symbol(self, symbol):
        """Classify a symbol into a category."""
        s = self.symbols
        if symbol in (s["note"], "*"):
            return "note"
        elif symbol in (s["problem"], "x", "×"):
            return "problem"
        elif symbol == s["learning"]:
            return "learning"
        elif symbol == s["idea"]:
            return "idea"
        elif symbol in (s["todo"], "[ ]"):
            return "todo"
        elif symbol in (s["done"], "[v]", "✓"):
            return "done"
        elif symbol in (s["migrate"], ">>", "→"):
            return "migrate"
        return "other"

    # ── Core Features ──

    def sync_daily_to_projects(self, date_str=None):
        """Sync daily log to projects/ directory."""
        if date_str is None:
            date_str = datetime.now().strftime("%Y-%m-%d")

        daily_path = self._daily_path(date_str)
        if not daily_path.exists():
            print(f"[SKIP] daily/{date_str}.md does not exist")
            return

        content = daily_path.read_text(encoding="utf-8")
        lines = content.split("\n")

        # Group lines by project tag
        project_lines = {}
        for line in lines:
            parsed = self._parse_log_line(line)
            if not parsed or not parsed["tags"]:
                continue
            for tag in parsed["tags"]:
                project_lines.setdefault(tag, []).append(line.strip())

        if not project_lines:
            print(f"[INFO] daily/{date_str}.md has no project tags, skipping sync")
            return

        for project, plines in project_lines.items():
            project_dir = self.root / "projects" / project
            project_dir.mkdir(parents=True, exist_ok=True)

            # Daily project log — incremental update with section anchors
            daily_project = project_dir / f"{date_str}.md"
            records_section = "\n".join(plines) + "\n\n"

            start_anchor = "<!-- TODAY_RECORDS_START -->"
            end_anchor = "<!-- TODAY_RECORDS_END -->"

            if daily_project.exists():
                existing = daily_project.read_text(encoding="utf-8")
                sidx = existing.find(start_anchor)
                eidx = existing.find(end_anchor)
                if sidx != -1 and eidx != -1:
                    # Replace only the records section
                    new_content = (
                        existing[:sidx + len(start_anchor)] + "\n\n"
                        + records_section
                        + existing[eidx:]
                    )
                    daily_project.write_text(new_content, encoding="utf-8")
                else:
                    # Fallback: full overwrite if anchors missing
                    header = (
                        f"# {project} — {date_str} DevLog\n\n"
                        f"> Auto-extracted from daily log, containing all @{project} tagged records\n\n"
                        f"## Today's Records\n\n"
                        f"{start_anchor}\n\n"
                    )
                    footer = (
                        f"{end_anchor}\n\n"
                        f"## Problems & Solutions\n\n"
                        f"<!-- Auto-extracted problem records, or detailed analysis by user -->\n"
                    )
                    daily_project.write_text(header + records_section + footer, encoding="utf-8")
            else:
                header = (
                    f"# {project} — {date_str} DevLog\n\n"
                    f"> Auto-extracted from daily log, containing all @{project} tagged records\n\n"
                    f"## Today's Records\n\n"
                    f"{start_anchor}\n\n"
                )
                footer = (
                    f"{end_anchor}\n\n"
                    f"## Problems & Solutions\n\n"
                    f"<!-- Auto-extracted problem records, or detailed analysis by user -->\n"
                )
                daily_project.write_text(header + records_section + footer, encoding="utf-8")

            # Monthly aggregation (avoid duplicates)
            month_str = date_str[:7]
            monthly_path = project_dir / f"{month_str}.md"

            if monthly_path.exists():
                monthly_content = monthly_path.read_text(encoding="utf-8")
            else:
                monthly_content = (
                    f"# {project} — {month_str} Monthly Report\n\n"
                    f"<!-- Monthly aggregation of all @{project} tagged records -->\n"
                )

            date_header = f"\n## {date_str}\n"
            if date_header not in monthly_content:
                monthly_content += date_header + "\n".join(plines) + "\n"
                monthly_path.write_text(monthly_content, encoding="utf-8")

        print(f"[OK] Synced {len(project_lines)} project logs (date: {date_str})")

    def archive_inbox(self):
        """Archive inbox.md to daily/ files."""
        inbox_path = self.root / "inbox.md"
        if not inbox_path.exists():
            print("[SKIP] inbox.md does not exist")
            return

        content = inbox_path.read_text(encoding="utf-8")
        lines = content.split("\n")

        inbox_pattern = (
            r'^\[(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})\]\s+'
            r'([·×○✓→*x!\-\[\]v>]+)\s+(.+)$'
        )

        archived = 0
        daily_records = {}

        for line in lines:
            m = re.match(inbox_pattern, line.strip())
            if not m:
                continue
            date_str, time_str, symbol, content = m.groups()
            daily_line = f"[{time_str}] {symbol} {content}"
            daily_records.setdefault(date_str, []).append(daily_line)
            archived += 1

        if not archived:
            print("[INFO] inbox.md has no records to archive")
            return

        for date_str, records in daily_records.items():
            daily_path = self._ensure_daily(date_str)
            daily_content = daily_path.read_text(encoding="utf-8")

            marker = "## 🕐 Interstitial Log"
            insert_text = "\n" + "\n".join(records) + "\n"

            if marker in daily_content:
                idx = daily_content.find(marker) + len(marker)
                comment = "<!-- AI appends records here -->"
                cidx = daily_content.find(comment, idx)
                if cidx != -1:
                    idx = cidx + len(comment)
                daily_content = daily_content[:idx] + insert_text + daily_content[idx:]
            else:
                daily_content += "\n" + marker + insert_text

            daily_path.write_text(daily_content, encoding="utf-8")
            print(f"[OK] Archived {len(records)} records to daily/{date_str}.md")

        # Clear inbox: keep only header lines before the first record
        header_lines = []
        for line in lines:
            if re.match(inbox_pattern, line.strip()):
                break
            header_lines.append(line)

        inbox_path.write_text("\n".join(header_lines).rstrip() + "\n", encoding="utf-8")
        print(f"[OK] inbox.md archived {archived} records and cleared")

    def generate_daily_stats(self, date_str=None):
        """Generate daily statistics table."""
        if date_str is None:
            date_str = datetime.now().strftime("%Y-%m-%d")

        daily_path = self._daily_path(date_str)
        if not daily_path.exists():
            print(f"[SKIP] daily/{date_str}.md does not exist")
            return

        content = daily_path.read_text(encoding="utf-8")
        lines = content.split("\n")

        stats = {
            "note": 0, "problem": 0, "learning": 0,
            "idea": 0, "todo": 0, "done": 0, "migrate": 0,
            "total": 0,
        }
        hashtag_stats = {}
        total_duration = 0

        for line in lines:
            parsed = self._parse_log_line(line)
            if not parsed:
                continue
            cat = self._classify_symbol(parsed["symbol"])
            if cat in stats:
                stats[cat] += 1
                stats["total"] += 1
            for ht in parsed.get("hashtags", []):
                hashtag_stats[ht] = hashtag_stats.get(ht, 0) + 1
            if "duration" in parsed:
                total_duration += parsed["duration"]

        if stats["total"] == 0:
            print(f"[INFO] daily/{date_str}.md has no records, skipping stats")
            return

        s = self.symbols

        def pct(n):
            return f"{round(n / stats['total'] * 100)}%"

        extra_lines = []
        if total_duration > 0:
            hours = round(total_duration / 60, 1)
            extra_lines.append(f"\n**Tracked Time**: {hours}h")
        if hashtag_stats:
            tags_str = ", ".join(f"#{ht} ({c})" for ht, c in sorted(hashtag_stats.items(), key=lambda x: -x[1]))
            extra_lines.append(f"\n**Hashtags**: {tags_str}")

        stats_table = (
            f"| Type | Count | Percentage |\n"
            f"|------|-------|------------|\n"
            f"| Note {s['note']} | {stats['note']} | {pct(stats['note'])} |\n"
            f"| Problem {s['problem']} | {stats['problem']} | {pct(stats['problem'])} |\n"
            f"| Learning {s['learning']} | {stats['learning']} | {pct(stats['learning'])} |\n"
            f"| Idea {s['idea']} | {stats['idea']} | {pct(stats['idea'])} |\n"
            f"| Todo {s['todo']}→{s['done']} | {stats['todo']}→{stats['done']} | {pct(stats['todo'] + stats['done'])} |"
            + "".join(extra_lines)
        )

        # Use anchor comments for robust table replacement, fallback to legacy markers
        start_anchor = "<!-- STATS_TABLE_START -->"
        end_anchor = "<!-- STATS_TABLE_END -->"
        start_idx = content.find(start_anchor)
        end_idx = content.find(end_anchor)

        if start_idx != -1 and end_idx != -1:
            before = content[:start_idx + len(start_anchor)]
            after = content[end_idx:]
            content = before + "\n" + stats_table + "\n" + after
        else:
            # Legacy fallback: use section headers
            start_marker = "## 📊 Daily Stats"
            end_marker = "## 🧠 Reflections"
            start_idx = content.find(start_marker)
            end_idx = content.find(end_marker)
            if start_idx != -1 and end_idx != -1:
                before = content[:start_idx + len(start_marker)]
                after = content[end_idx:]
                content = (
                    before + "\n\n"
                    "> Auto-generated by `sync.py --daily-stats`\n\n"
                    + stats_table + "\n\n"
                    + after
                )

        daily_path.write_text(content, encoding="utf-8")
        print(f"[OK] Generated stats for daily/{date_str}.md ({stats['total']} records)")

    def generate_weekly_report(self, week_start=None):
        """Generate weekly report."""
        if week_start is None:
            today = datetime.now()
            week_start = today - timedelta(days=today.weekday() + 7)

        week_end = week_start + timedelta(days=6)
        week_range = (
            f"{week_start.strftime('%Y-%m-%d')} ~ {week_end.strftime('%Y-%m-%d')}"
        )

        all_stats = {
            "note": 0, "problem": 0, "learning": 0,
            "idea": 0, "todo": 0, "done": 0, "total": 0,
        }
        project_stats = {}
        hashtag_stats = {}
        problems = []
        ideas_list = []
        moods = []
        total_duration = 0

        for i in range(7):
            date = week_start + timedelta(days=i)
            date_str = date.strftime("%Y-%m-%d")
            path = self._daily_path(date_str)
            if not path.exists():
                continue

            content = path.read_text(encoding="utf-8")

            # Extract mood scores
            for m in re.finditer(r'\(mood:\s*(\d)/5\)', content, re.IGNORECASE):
                moods.append(int(m.group(1)))

            for line in content.split("\n"):
                parsed = self._parse_log_line(line)
                if not parsed:
                    continue

                cat = self._classify_symbol(parsed["symbol"])
                if cat in all_stats:
                    all_stats[cat] += 1
                    all_stats["total"] += 1

                for tag in parsed["tags"]:
                    project_stats[tag] = project_stats.get(tag, 0) + 1

                for ht in parsed.get("hashtags", []):
                    hashtag_stats[ht] = hashtag_stats.get(ht, 0) + 1

                if "duration" in parsed:
                    total_duration += parsed["duration"]

                if cat == "problem":
                    problems.append(f"{date_str} {line.strip()}")
                elif cat == "idea":
                    ideas_list.append(f"{date_str} {line.strip()}")

        total_todo = all_stats["todo"] + all_stats["done"]
        done_rate = round(all_stats["done"] / max(total_todo, 1) * 100)
        avg_mood = round(sum(moods) / len(moods), 1) if moods else None
        hours = round(total_duration / 60, 1)

        report_lines = [
            f"# {week_range} Weekly Review",
            "",
            f"> Auto-generated, period: {week_range}",
            "",
            "## 📈 Weekly Overview",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total Records | {all_stats['total']} |",
            f"| Todo Completion Rate | {done_rate}% |",
            f"| Problems | {all_stats['problem']} |",
            f"| Learning | {all_stats['learning']} |",
            f"| Ideas | {all_stats['idea']} |",
        ]
        if avg_mood is not None:
            report_lines.append(f"| Avg Mood | {avg_mood}/5 |")
        if total_duration > 0:
            report_lines.append(f"| Tracked Time | {hours}h |")
        report_lines += ["",
            "## 🏗️ Project Time Distribution",
            "",
        ]
        for proj, count in sorted(project_stats.items(), key=lambda x: -x[1]):
            report_lines.append(f"- @{proj}: {count} records")

        if hashtag_stats:
            report_lines += ["", "## 🏷️ Hashtags", ""]
            for ht, count in sorted(hashtag_stats.items(), key=lambda x: -x[1]):
                report_lines.append(f"- #{ht}: {count}")

        report_lines += ["", "## ⚠️ Problems This Week", ""]
        if problems:
            for p in problems:
                report_lines.append(f"- {p}")
        else:
            report_lines.append("None")

        report_lines += ["", "## 💡 Ideas", ""]
        if ideas_list:
            for idea in ideas_list:
                report_lines.append(f"- {idea}")
        else:
            report_lines.append("None")

        report_lines += ["", "## 🎯 Next Week Plan", "", "<!-- Fill in by user -->", ""]

        report_path = self.root / "daily" / f"weekly-{week_start.strftime('%Y-%m-%d')}.md"
        report_path.write_text("\n".join(report_lines), encoding="utf-8")
        print(f"[OK] Generated weekly report: {report_path}")

    # ── Entry Point ──

    def run(self, args):
        executed = False

        if args.archive_inbox:
            self.archive_inbox()
            executed = True

        if args.daily_stats:
            self.generate_daily_stats(args.date)
            executed = True

        if args.sync:
            self.sync_daily_to_projects(args.date)
            self.generate_daily_stats(args.date)
            executed = True

        if args.weekly:
            self.generate_weekly_report()
            executed = True

        if args.date and not executed:
            self.sync_daily_to_projects(args.date)
            self.generate_daily_stats(args.date)
            executed = True

        if not executed:
            self.sync_daily_to_projects()
            self.generate_daily_stats()


def main():
    parser = argparse.ArgumentParser(description="DevLog Sync Script")
    parser.add_argument("--date", help="Specify date (YYYY-MM-DD), default today")
    parser.add_argument("--archive-inbox", action="store_true",
                        help="Archive inbox.md to daily/")
    parser.add_argument("--daily-stats", action="store_true",
                        help="Generate daily statistics table")
    parser.add_argument("--weekly", action="store_true",
                        help="Generate weekly report")
    parser.add_argument("--sync", action="store_true",
                        help="Sync daily to projects/ and generate stats")
    parser.add_argument("--root", help="Override DevLog root directory")

    args = parser.parse_args()

    if args.date and not any([args.archive_inbox, args.daily_stats, args.weekly, args.sync]):
        args.sync = True

    sync = DevLogSync(root_dir=args.root)
    sync.run(args)


if __name__ == "__main__":
    main()
